const COURSE = [
  { title: "How the web works", body: "Every website is a conversation between your browser and a server. When you enter an address, the browser requests files—usually HTML, CSS, and JavaScript—and turns them into the page you see.", point: "HTML provides structure, CSS shapes the presentation, and JavaScript adds behavior." },
  { title: "Structure with HTML", body: "HTML describes meaning. Headings create a clear outline, paragraphs hold ideas, and links connect one resource to another. Accessible HTML helps every learner and device understand your content.", point: "Choose elements for what they mean, not merely how they look." },
  { title: "Style with CSS", body: "CSS controls the visual layer: type, spacing, colors, and responsive layouts. Rules select HTML elements and apply declarations such as color, margin, or display.", point: "Good CSS makes a design adapt gracefully to screens of all sizes." },
  { title: "Knowledge check", body: "You have reached the final lesson. Answer this short check-in to record your score in your progress file.", point: "Your score is saved automatically and included when you download your JSON backup.", quiz: { question: "Which technology gives a web page its structure?", options: ["CSS", "HTML", "JavaScript"], answer: 1 } }
];
const KEY = "learnkeep-course-progress";
let state = { version: 1, courseId: "web-foundation", updatedAt: null, completedLessons: [], quizScores: {} };
let current = 0;
const $ = (id) => document.getElementById(id);

function load() { try { const saved = JSON.parse(localStorage.getItem(KEY)); if (saved && saved.courseId === state.courseId) state = { ...state, ...saved, completedLessons: saved.completedLessons || [], quizScores: saved.quizScores || {} }; } catch { localStorage.removeItem(KEY); } }
function save() { state.updatedAt = new Date().toISOString(); $("saveState").classList.add("saving"); $("saveState").innerHTML = "<i></i> Saving…"; localStorage.setItem(KEY, JSON.stringify(state)); setTimeout(() => { $("saveState").classList.remove("saving"); $("saveState").innerHTML = "<i></i> Saved on this device"; }, 250); }
function complete(index) { if (!state.completedLessons.includes(index)) { state.completedLessons.push(index); save(); } render(); }
function renderNav() { $("lessonList").innerHTML = COURSE.map((lesson, i) => `<button class="lesson-item ${i === current ? "active" : ""} ${state.completedLessons.includes(i) ? "done" : ""}" data-lesson="${i}"><span class="num">${state.completedLessons.includes(i) ? "✓" : i + 1}</span><span>${lesson.title}</span></button>`).join(""); document.querySelectorAll("[data-lesson]").forEach((button) => button.onclick = () => { current = Number(button.dataset.lesson); render(); }); }
function renderLesson() { const lesson = COURSE[current]; const done = state.completedLessons.includes(current); let content = `<p class="lesson-kicker">Lesson ${current + 1} of ${COURSE.length}</p><h2>${lesson.title}</h2><p>${lesson.body}</p><p class="key-point">${lesson.point}</p>`;
  if (lesson.quiz) { const score = state.quizScores.finalCheck; const locked = score !== undefined; content += `<section class="quiz"><h3>${lesson.quiz.question}</h3><div class="answers">${lesson.quiz.options.map((option, i) => `<button class="answer ${locked ? (i === lesson.quiz.answer ? "correct" : score.selected === i ? "wrong" : "") : ""}" data-answer="${i}" ${locked ? "disabled" : ""}>${option}</button>`).join("")}</div>${locked ? `<p class="quiz-result ${score.correct ? "good" : "bad"}">${score.correct ? "Correct — great work!" : "Not quite — HTML gives a page its structure."} Score saved: ${score.correct ? "1" : "0"}/1</p>` : ""}</section>`; }
  content += `<button class="complete-button" id="completeButton" ${done ? "disabled" : ""}>${done ? "✓ Lesson completed" : "Mark lesson complete"}</button>`; $("lessonPanel").innerHTML = content; $("completeButton").onclick = () => complete(current);
  document.querySelectorAll("[data-answer]").forEach((button) => button.onclick = () => { const selected = Number(button.dataset.answer); state.quizScores.finalCheck = { selected, correct: selected === lesson.quiz.answer, answeredAt: new Date().toISOString() }; complete(current); }); }
function renderProgress() { const completeCount = state.completedLessons.length; const percent = Math.round((completeCount / COURSE.length) * 100); $("progressLabel").textContent = `${completeCount} of ${COURSE.length} lessons complete`; $("progressPercent").textContent = `${percent}%`; $("progressBar").style.width = `${percent}%`; }
function render() { renderNav(); renderLesson(); renderProgress(); }
load(); render(); if ("serviceWorker" in navigator) window.addEventListener("load", () => navigator.serviceWorker.register("./sw.js"));
